ecommerce/src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Utilisateur implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="float")
     */
    private $solde;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getSolde(): ?float
    {
        return $this->solde;
    }

    public function setSolde(float $solde): self
    {
        $this->solde = $solde;

        return $this;
    }
}

ecommerce/src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateur;
use App\Form\MotPasseFormType;
use App\Form\RegistrationFormType;
use App\Form\SoldeFormType;
use App\Form\UtilisateurFormType;
use App\Security\ConnexionAuthenticator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Guard\GuardAuthenticatorHandler;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="app_login")
     */
    public function login(AuthenticationUtils $outils): Response
    {
        $erreur = $outils->getLastAuthenticationError();
        $nom_utilisateur = $outils->getLastUsername();

        return $this->render('security/login.html.twig', ['nom_utilisateur' => $nom_utilisateur, 'erreur' => $erreur]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout()
    {
        throw new \LogicException('Cette méthode peut être vide - elle sera interceptée par la clé de déconnexion sur votre pare-feu.');
    }



    /**
     * @Route("/register", name="app_register")
     */
    public function register(Request $requete, UserPasswordEncoderInterface $encode, GuardAuthenticatorHandler $garde, ConnexionAuthenticator $indentification, EntityManagerInterface $manager_interface): Response
    {
        $utilisateur = new Utilisateur();
        $formulaire = $this->createForm(RegistrationFormType::class, $utilisateur);
        $formulaire->handleRequest($requete);

        if ($formulaire->isSubmitted() && $formulaire->isValid()) {
            $utilisateur->setPassword(
                $encode->encodePassword(
                    $utilisateur,
                    $formulaire->get('plainPassword')->getData()
                )
            );
            $utilisateur->setSolde(0);
            $manager_interface->persist($utilisateur);
            $manager_interface->flush();

            return $garde->authenticateUserAndHandleSuccess(
                $utilisateur,
                $requete,
                $indentification,
                'main'
            );
            return $this->redirect('/');
        }

        return $this->render('security/register.html.twig', [
            'formulaire' => $formulaire->createView(),
        ]);
    }

    /**
     * @Route("/modification/{id}", name="utilisateur.modification")
     */
    public function modification_utilisateur(Utilisateur $utilisateur, Request $requete, GuardAuthenticatorHandler $garde, ConnexionAuthenticator $indentification, EntityManagerInterface $manager_interface): Response
    {

        $formulaire = $this->createForm(UtilisateurFormType::class, $utilisateur, [
            "attr" => [
                "class" => "formulaire_modification_utilisateur",
            ]
        ]);

        $formulaire->handleRequest($requete);
        if ($formulaire->isSubmitted() && $formulaire->isValid()) {
            $manager_interface->persist($utilisateur);
            $manager_interface->flush();

            if ($utilisateur->getRoles() == ["ROLE_USER"]) {

                return $garde->authenticateUserAndHandleSuccess(
                    $utilisateur,
                    $requete,
                    $indentification,
                    'main'
                );
                return $this->redirect('/profil');
            } else {
                return $this->redirect('/gestion');
            }
        }

        return $this->render('security/modification.html.twig', [
            'formulaire' => $formulaire->createView(),
            'utilisateur' => $utilisateur,
        ]);
    }

    /**
     * @Route("/modification_mot_passe/{id}", name="utilisateur.mot_passe")
     */
    public function modification_mot_passe(Utilisateur $utilisateur, Request $requete, UserPasswordEncoderInterface $encode,  GuardAuthenticatorHandler $garde, ConnexionAuthenticator $indentification, EntityManagerInterface $manager_interface): Response
    {

        $formulaire = $this->createForm(MotPasseFormType::class, $utilisateur, [
            "attr" => [
                "class" => "formulaire_modification_mot_passe",
            ]
        ]);

        $formulaire->handleRequest($requete);
        if ($formulaire->isSubmitted() && $formulaire->isValid()) {
            $utilisateur->setPassword(
                $encode->encodePassword(
                    $utilisateur,
                    $formulaire->get('plainPassword')->getData()
                )
            );
            $manager_interface->persist($utilisateur);
            $manager_interface->flush();


            return $garde->authenticateUserAndHandleSuccess(
                $utilisateur,
                $requete,
                $indentification,
                'main'
            );
            return $this->redirect('/profil');
        }

        return $this->render('security/modification_mot_passe.html.twig', [
            'formulaire' => $formulaire->createView(),
            'utilisateur' => $utilisateur,
        ]);
    }

    /**
     * @Route("/solde/{id}", name="utilisateur.solde")
     */
    public function solde(Utilisateur $utilisateur, Request $requete, EntityManagerInterface $manager_interface): Response
    {

        $solde_precedant = $utilisateur->getSolde();

        $formulaire = $this->createForm(SoldeFormType::class, $utilisateur, [
            "attr" => [
                "class" => "formulaire_modification_solde",
            ]
        ]);

        $formulaire->handleRequest($requete);
        if ($formulaire->isSubmitted() && $formulaire->isValid()) {
            $ajout_solde = $utilisateur->getSolde();
            $utilisateur->setSolde($solde_precedant + $ajout_solde);
            $manager_interface->persist($utilisateur);
            $manager_interface->flush();
            return $this->redirect('/profil');
        }

        return $this->render('security/modification_solde.html.twig', [
            'formulaire' => $formulaire->createView(),
            'utilisateur' => $utilisateur,
        ]);
    }

    /**
     * @Route("/supprimer/{id}", name="utilisateur.supprimer")
     */
    public function supprimer_utilisateur(Utilisateur $utilisateur, EntityManagerInterface $manager_interface): Response
    {
        $manager_interface->remove($utilisateur);
        $manager_interface->flush();
        return $this->redirect('/logout');
    }
}

ecommerce/templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Page Connexion
{% endblock %}

{% block body %}
	<div class="row justify-content-center">
		<div class="col-sm-3">
			<a href="/" role="button" class="btn bouton">Retour</a>
		</div>
	</div>
	<form method="post">
		{% if erreur %}
			<div class="alert alert-danger">{{ erreur.messageKey|trans(erreur.messageData, 'security') }}</div>
		{% endif %}

		{% if app.user %}
			<div class="mb-3">
				Vous êtez connecté sous
				{{ app.user.username }},
				<a href="{{ path('app_logout') }}">Déconnexion</a>
			</div>
		{% endif %}
		<div class="row justify-content-center">
			<h1 class="h3 mb-3 font-weight-normal">Connectez-vous</h1>
		</div>
		<div class="row justify-content-center">
			<div class="col-sm-3">
				<input type="email" value="{{ nom_utilisateur }}" name="email" id="inputEmail" class="form-control" placeholder="Email" required autofocus>
			</div>
		</div>
		<div class="row justify-content-center">
			<div class="col-sm-3">
				<input type="password" name="password" id="inputPassword" class="form-control" placeholder="Mot de Passe" required>
			</div>
		</div>
		<input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
		<div class="row justify-content-center">
			<button class="btn bouton" type="submit">
				Connexion
			</button>
		</div>
	</form>
{% endblock %}

ecommerce/templates/security/modification.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Page modification Profil
{% endblock %}

{% block body %}
	{% for flashError in app.flashes('verify_email_error') %}
		<div class="alert alert-danger" role="alert">{{ flashError }}</div>
	{% endfor %}

	{% if is_granted('ROLE_ADMIN')%}
		<div class="row justify-content-center">
			<h1>Modification
				{{utilisateur.prenom}}
				{{utilisateur.nom}}
			</h1>
		</div>
		<div class="row justify-content-center">
			<div class="col-sm-3">
				<a href="/gestion" role="button" class="btn bouton">Retour</a>
			</div>
		</div>
	{% else %}
		<div class="row justify-content-center">
			<h1>Modification Profil</h1>
		</div>
		<div class="row justify-content-center">
			<div class="col-sm-3">
				<a href="/profil" role="button" class="btn btn-primary">Retour</a>
			</div>
		</div>
	{% endif %}

	{{ form_start(formulaire) }}
	<div class="row justify-content-center">
		{{ form_widget(formulaire.prenom) }}
	</div>
	<div class="row justify-content-center">
		{{ form_widget(formulaire.nom) }}
	</div>
	<div class="row justify-content-center">
		{{ form_widget(formulaire.email) }}
	</div>
	<div class="row justify-content-center">
		{{ form_errors(formulaire.email) }}
	</div>
	<div class="row justify-content-center">
		{{ form_widget(formulaire.date_naissance) }}
	</div>
	<div class="row justify-content-center">
		{{ form_errors(formulaire.date_naissance) }}
	</div>
	<div class="row justify-content-center">
		{{ form_row(formulaire.Modifier) }}
	</div>
	{{ form_end(formulaire) }}
{% endblock %}

ecommerce/templates/security/modification_mot_passe.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Page modification Mot de passe
{% endblock %}

{% block body %}
	{% for flashError in app.flashes('verify_email_error') %}
		<div class="alert alert-danger" role="alert">{{ flashError }}</div>
	{% endfor %}
	<div class="row justify-content-center">
		<h1>Modification Mot de Passe</h1>
	</div>
	<div class="row justify-content-center">
		<div class="col-sm-3">
			<a href="/profil" role="button" class="btn bouton">Retour</a>
		</div>
	</div>

	{{ form_start(formulaire) }}
	<div class="row justify-content-center">
		{{ form_widget(formulaire.plainPassword) }}
	</div>
	<div class="row justify-content-center">
		{{ form_errors(formulaire.plainPassword) }}
	</div>
	<div class="row justify-content-center">
		{{ form_row(formulaire.Modifier) }}
	</div>
	{{ form_end(formulaire) }}
{% endblock %}

ecommerce/templates/security/modification_solde.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Page Rechargement Solde
{% endblock %}

{% block body %}
	{% for flashError in app.flashes('verify_email_error') %}
		<div class="alert alert-danger" role="alert">{{ flashError }}</div>
	{% endfor %}
	<div class="row justify-content-center">
		<h1>Rechargement Solde</h1>
	</div>
	<div class="row justify-content-center">
		<div class="col-sm-3">
			<a href="/profil" role="button" class="btn bouton">Retour</a>
		</div>
	</div>

	{{ form_start(formulaire) }}
	<div class="row justify-content-center">
		{{ form_widget(formulaire.solde) }}
	</div>
	<div class="row justify-content-center">
		{{ form_errors(formulaire.solde) }}
	</div>
	<div class="row justify-content-center">
		{{ form_row(formulaire.Recharger) }}
	</div>
	{{ form_end(formulaire) }}
{% endblock %}

ecommerce/templates/security/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Page Inscription
{% endblock %}

{% block body %}
	{% for flashError in app.flashes('verify_email_error') %}
		<div class="alert alert-danger" role="alert">{{ flashError }}</div>
	{% endfor %}

	<h1 class="row justify-content-center">Inscription</h1>

	<div class="row justify-content-center">
		<div class="col-sm-3">
			<a href="/" role="button" class="btn bouton">Retour</a>
		</div>
	</div>

	{{ form_start(formulaire) }}
	<div class="row justify-content-center">
		{{ form_widget(formulaire.prenom) }}
	</div>
	<div class="row justify-content-center">
		{{ form_widget(formulaire.nom) }}
	</div>
	<div class="row justify-content-center">
		{{ form_widget(formulaire.email) }}
	</div>
	<div class="row justify-content-center">
		{{ form_errors(formulaire.email) }}
	</div>
	<div class="row justify-content-center">
		{{ form_widget(formulaire.plainPassword) }}
	</div>
	<div class="row justify-content-center">
		{{ form_errors(formulaire.plainPassword) }}
	</div>
	<div class="row justify-content-center">
		{{ form_widget(formulaire.date_naissance) }}
	</div>
	<div class="row justify-content-center">
		{{ form_errors(formulaire.date_naissance) }}
	</div>
	<div class="row justify-content-center">
		{{ form_row(formulaire.Inscription) }}
	</div>
	{{ form_end(formulaire) }}
{% endblock %}